### ISSUE TITLE
Multiple notifications

### ISSUE THREAD

**Issue by brenthorn** [w1ld3r/crypto-signal#16]
Hi, is there a way to stop recieving signals multiple times.? 

I have RSI set at hot 70 cold 30 
1h,4h,12h,1d timeframes 
update_interval set at 1600
alert_frequency: once

I constantly recieve a lot of notifications in those timeframes while the RSI is hot or cold even though alert frequency is set to once. It is not just the RSI indicator.! I have tested with EMA crossovers and MACD crossovers too. Is there somewhere I can look in notification.py to stop this from happening.?

Thank You

**Comment by w1ld3r** [comment]
Hello, You can try to increase the `update_interval`:
```yaml
settings:
   log_level: INFO
  update_interval: 120
  start_worker_interval: 2
  market_data_chunk_size: 1
```
