### ISSUE TITLE
[FEATURE] Multiple Telegram notifier 

### ISSUE THREAD

**Issue by velajos** [w1ld3r/crypto-signal#26]
How could notifications be sent to two or more Telegram accounts at the same time?

**Comment by w1ld3r** [comment]
I don't think it's avaliable for now. Have you tried to define multiple telegram object in the `config.yml` file ?

**Comment by velajos** [comment]
> I don't think it's avaliable for now. Have you tried to define multiple telegram object in the `config.yml` file ?

Yes, but I got the notification only for the first Telegram in the config.yml

**Comment by w1ld3r** [comment]
Ok, I will implement it asap.

**Comment by velajos** [comment]
> Ok, I will implement it asap.

Ok, let me know please

**Comment by velajos** [comment]
> Ok, I will implement it asap.

It could be something like this:

notifiers:
    telegram:
        required:
            token1: 1847324294XXXkCdO3q5KZv
            chat_id1: -XXX1234130
            token2: 1847324294XXXkCdO3q5KZv
            chat_id2: -XXX1234130
            token3: 1847324294XXXkCdO3q5KZv
            chat_id3: -XXX1234130

And so on, without a specific limit

**Comment by velajos** [comment]
Please let me know when the Feature is implemented

**Comment by w1ld3r** [comment]
Can you check the new [push](https://github.com/w1ld3r/crypto-signal/commit/56851a7097caae081446b4ff873b3ae11c1d37a8) ?

**Comment by w1ld3r** [comment]
You can use it like that:
```yml
notifiers:
    telegram_00:
        required:
            token: XXX
            chat_id: YYY
        optional:
            parse_mode: html
            template: "[{{market}}] {{indicator}} {{status}} {{values}} {{ '\n' -}}"
    telegram_01:
        required:
            token: XXX
            chat_id: YYY
        optional:
            parse_mode: html
            template: "[{{market}}] {{indicator}} {{status}} {{values}} {{ '\n' -}}"
```
