### ISSUE TITLE
[FEATURE] Request Binance Futures Api

### ISSUE THREAD

**Issue by velajos** [w1ld3r/crypto-signal#31]
Could the BINANCE Futures Api be added as an option? (which only works with USDT pairs)

**Comment by w1ld3r** [comment]
You can pull the new [push](https://github.com/w1ld3r/crypto-signal/commit/44f27b91a7ce49783bd193cb46c7c65d09f672a9) and change your config file with the option `future` to `true`:
```yaml
exchanges:
    binance:
        required:
            enabled: true
        all_pairs:
            - USDT
        future: true
```
Please, @Juanjacinto123, let me know if you are satisfied with the result. You'll have 118 pairs on binance futures.

**Comment by Hackmole** [comment]
How can I make use of this?

**Comment by w1ld3r** [comment]
> How can I make use of this?

Please, if you face an issue create your own ticket.

**Comment by Majenunez** [comment]
> ```yaml
> future: true
> ```

So far I am testing it and it works as expected.

But when I use the "top_pairs" option, I get the following error:

_" File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tenacity\__init__.py", line 433, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\user\Documents\GitHub\crypto-signal-futures\app\exchange.py", line 151, in get_top_markets
    values, dtype=[('market', 'U10'), ('volume', int)])
OverflowError: Python int too large to convert to C long"_

**Comment by Majenunez** [comment]
I am currently using this settings :
 
_"update_interval: 260
    start_worker_interval: 20
    market_data_chunk_size: 10"_

And eventually I get this error:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "app.py", line 100, in run
    self.behaviour.run(self.market_data, self.settings['output_mode'])
  File "C:\Users\user\Documents\GitHub\crypto-signal-futures\app\behaviour.py", line 74, in run
    self.notifier.notify_all(new_result)
  File "C:\Users\user\Documents\GitHub\crypto-signal-futures\app\notification.py", line 157, in notify_all
    messages = self.get_indicator_messages(new_analysis)
  File "C:\Users\user\Documents\GitHub\crypto-signal-futures\app\notification.py", line 671, in get_indicator_messages
    '/')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by velajos** [comment]
> > ```yaml
> > future: true
> > ```
> 
> So far I am testing it and it works as expected.
> 
> But when I use the "top_pairs" option, I get the following error:
> 
> _" File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\concurrent\futures_base.py", line 428, in result
> return self.__get_result()
> File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\concurrent\futures_base.py", line 384, in __get_result raise self._exception File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\tenacity__init__.py", line 433, in **call** result = fn(*args, **kwargs) File "C:\Users\user\Documents\GitHub\crypto-signal-futures\app\exchange.py", line 151, in get_top_markets values, dtype=[('market', 'U10'), ('volume', int)]) OverflowError: Python int too large to convert to C long"_

Same thing happens to me @w1ld3r

**Comment by velajos** [comment]
> I am currently using this settings :
> 
> _"update_interval: 260 start_worker_interval: 20 market_data_chunk_size: 10"_
> 
> And eventually I get this error:
> 
> Traceback (most recent call last):
> File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
> self.run()
> File "app.py", line 100, in run
> self.behaviour.run(self.market_data, self.settings['output_mode'])
> File "C:\Users\user\Documents\GitHub\crypto-signal-futures\app\behaviour.py", line 74, in run
> self.notifier.notify_all(new_result)
> File "C:\Users\user\Documents\GitHub\crypto-signal-futures\app\notification.py", line 157, in notify_all
> messages = self.get_indicator_messages(new_analysis)
> File "C:\Users\user\Documents\GitHub\crypto-signal-futures\app\notification.py", line 671, in get_indicator_messages
> '/')
> ValueError: not enough values to unpack (expected 2, got 1)

Hi @w1ld3r ,

Same error with default settings: 

update_interval: 300

Traceback (most recent call last):

  File "C:\Users\flia\Documents\GitHub\crypto-signal\app\notification.py", line 157, in notify_all
    messages = self.get_indicator_messages(new_analysis)
  File "C:\Users\flia\Documents\GitHub\crypto-signal\app\notification.py", line 671, in get_indicator_messages
    '/')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by w1ld3r** [comment]
Sorry, I'll only be available this weekend to resolve the issue.

**Comment by velajos** [comment]
> Sorry, I'll only be available this weekend to resolve the issue.

No problem, thanks for taking the time to help.

**Comment by w1ld3r** [comment]
Can you check the new push ?

**Comment by velajos** [comment]
> Can you check the new push ?

Yes. 

Now, the "Top pairs" feature is working fine.

**Comment by velajos** [comment]
@w1ld3r Please check the other question I told you about a few days ago. 

Regarding this: [FEATURE] Avoiding Spam in Notifications from Conditionals #34

**Comment by velajos** [comment]
> > Can you check the new push ?
> 
> Yes.
> 
> Now, the "Top pairs" feature is working fine.

@w1ld3r I made a mistake when I answered this, the mistake was that I did not have the "future: true" option and the "top_pairs" option active.

Now that I have it active,  I keep getting the following error:

  _File "C:\Users\flia\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "C:\Users\flia\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\flia\AppData\Local\Programs\Python\Python37\lib\site-packages\tenacity\__init__.py", line 433, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\flia\Documents\GitHub\crypto-signal-wilder-condit\crypto-signal\app\exchange.py", line 151, in get_top_markets
    values, dtype=[('market', 'U10'), ('volume', int)])
OverflowError: Python int too large to convert to C long_

This is my config regarding the exchange:
```yml
exchanges:

    binance:
        required:
            enabled: true
        all_pairs:
            - USDT
            #- BTC
        future: true            
        exclude:
            - USDC
            - PAX
            - BUSD
            - TUSD
            - EUR
            - SUSD
            - GBP
            - UTK
            - BTC
        top_pairs: 100
```

**Comment by velajos** [comment]
> > I am currently using this settings :
> > _"update_interval: 260 start_worker_interval: 20 market_data_chunk_size: 10"_
> > And eventually I get this error:
> > Traceback (most recent call last):
> > File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
> > self.run()
> > File "app.py", line 100, in run
> > self.behaviour.run(self.market_data, self.settings['output_mode'])
> > File "C:\Users\user\Documents\GitHub\crypto-signal-futures\app\behaviour.py", line 74, in run
> > self.notifier.notify_all(new_result)
> > File "C:\Users\user\Documents\GitHub\crypto-signal-futures\app\notification.py", line 157, in notify_all
> > messages = self.get_indicator_messages(new_analysis)
> > File "C:\Users\user\Documents\GitHub\crypto-signal-futures\app\notification.py", line 671, in get_indicator_messages
> > '/')
> > ValueError: not enough values to unpack (expected 2, got 1)
> 
> Hi @w1ld3r ,
> 
> Same error with default settings:
> 
> update_interval: 300
> 
> Traceback (most recent call last):
> 
> File "C:\Users\flia\Documents\GitHub\crypto-signal\app\notification.py", line 157, in notify_all
> messages = self.get_indicator_messages(new_analysis)
> File "C:\Users\flia\Documents\GitHub\crypto-signal\app\notification.py", line 671, in get_indicator_messages
> '/')
> ValueError: not enough values to unpack (expected 2, got 1)

@w1ld3r  This error was fixed successfully.

**Comment by w1ld3r** [comment]
Can you try without ` top_pairs: 100` option ?

**Comment by velajos** [comment]
> Can you try without ` top_pairs: 100` option ?

Yes, without  the "top_pairs: 100` option, Error does not occur

**Comment by w1ld3r** [comment]
Ì didn't get any error using this config file:
```yml
settings:
    log_level: INFO
    update_interval: 10
    start_worker_interval: 2
    market_data_chunk_size: 1

exchanges:
    binance:
        required:
            enabled: true
        all_pairs:
            - USDT
            #- BTC
        future: true            
        exclude:
            - USDC
            - PAX
            - BUSD
            - TUSD
            - EUR
            - SUSD
            - GBP
            - UTK
            - BTC
        top_pairs: 100
        
indicators:
    bbp:
        - enabled: false
    ma_crossover:
        - enabled: false
    rsi:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 100
          cold: 0
          candle_period: 15m 
          period_count: 14
          mute_cold: false
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 100
          cold: 0
          candle_period: 1h
          period_count: 14
          mute_cold: false
    ma_ribbon:
        - enabled: false     
    macd:
        - enabled: false
    iiv:
        - enabled: false
    stoch_rsi:
        - enabled: false
    momentum:
        - enabled: false
    obv:
        - enabled: false
    mfi:
        - enabled: false
    ichimoku:
        - enabled: false

informants:
    lrsi:
        - enabled: false
    sma:
        - enabled: false       
    ema:
        - enabled: false
    vwap:
        - enabled: false
    bollinger_bands:
        - enabled: false
    ohlcv:
        - enabled: true
          signal:
            - high
            - low
            - close
          candle_period: 1h
          period_count: 14
        - enabled: true
          signal:
            - high
            - low
            - close
          candle_period: 15m
          period_count: 14  
        
conditionals:
  - label: "Buy"
    hot:
      - rsi: 0
      - rsi: 1
  - label: "Sell"
    cold:
      - rsi: 0
      - rsi: 1

notifiers:
    telegram_01:
        required:
            token: XXX
            chat_id: YYY
        optional:
            parse_mode: html
            template: "{{ market }} 
            BUY {{ price_value['1h'].close }} 
            SL: {{ decimal_format|format(price_value['1h'].low * 0.9) }} 
            TP: {{ decimal_format|format(price_value['1h'].close * 1.02) }} {{ decimal_format|format(price_value['1h'].close * 1.04) }} "
```

**Comment by velajos** [comment]
> Ì didn't get any error using this config file:
> 
> ```yaml
> settings:
>     log_level: INFO
>     update_interval: 10
>     start_worker_interval: 2
>     market_data_chunk_size: 1
> 
> exchanges:
>     binance:
>         required:
>             enabled: true
>         all_pairs:
>             - USDT
>             #- BTC
>         future: true            
>         exclude:
>             - USDC
>             - PAX
>             - BUSD
>             - TUSD
>             - EUR
>             - SUSD
>             - GBP
>             - UTK
>             - BTC
>         top_pairs: 100
>         
> indicators:
>     bbp:
>         - enabled: false
>     ma_crossover:
>         - enabled: false
>     rsi:
>         - enabled: true
>           alert_enabled: true
>           alert_frequency: once
>           signal:
>             - rsi
>           hot: 100
>           cold: 0
>           candle_period: 15m 
>           period_count: 14
>           mute_cold: false
>         - enabled: true
>           alert_enabled: true
>           alert_frequency: once
>           signal:
>             - rsi
>           hot: 100
>           cold: 0
>           candle_period: 1h
>           period_count: 14
>           mute_cold: false
>     ma_ribbon:
>         - enabled: false     
>     macd:
>         - enabled: false
>     iiv:
>         - enabled: false
>     stoch_rsi:
>         - enabled: false
>     momentum:
>         - enabled: false
>     obv:
>         - enabled: false
>     mfi:
>         - enabled: false
>     ichimoku:
>         - enabled: false
> 
> informants:
>     lrsi:
>         - enabled: false
>     sma:
>         - enabled: false       
>     ema:
>         - enabled: false
>     vwap:
>         - enabled: false
>     bollinger_bands:
>         - enabled: false
>     ohlcv:
>         - enabled: true
>           signal:
>             - high
>             - low
>             - close
>           candle_period: 1h
>           period_count: 14
>         - enabled: true
>           signal:
>             - high
>             - low
>             - close
>           candle_period: 15m
>           period_count: 14  
>         
> conditionals:
>   - label: "Buy"
>     hot:
>       - rsi: 0
>       - rsi: 1
>   - label: "Sell"
>     cold:
>       - rsi: 0
>       - rsi: 1
> 
> notifiers:
>     telegram_01:
>         required:
>             token: XXX
>             chat_id: YYY
>         optional:
>             parse_mode: html
>             template: "{{ market }} 
>             BUY {{ price_value['1h'].close }} 
>             SL: {{ decimal_format|format(price_value['1h'].low * 0.9) }} 
>             TP: {{ decimal_format|format(price_value['1h'].close * 1.02) }} {{ decimal_format|format(price_value['1h'].close * 1.04) }} "
> ```

I'm using this settings:

settings:
    log_level: INFO
    update_interval: 350
    start_worker_interval: 15
    market_data_chunk_size: 5

**Comment by w1ld3r** [comment]
Still not getting any errors.

**Comment by velajos** [comment]
> Still not getting any errors.

This is the full configuration:
```yml
settings:
    log_level: INFO
    enable_charts: false
    update_interval: 350
    start_worker_interval: 15
    market_data_chunk_size: 5

exchanges:
    binance:
        required:
            enabled: true
        all_pairs:
            - USDT
            #- BTC
        future: true            
        exclude:
            - USDC
            - PAX
            - BUSD
            - TUSD
            - EUR
            - SUSD
            - GBP
            - UTK
            - BTC
        top_pairs: 100 
        
indicators:
    bbp:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          candle_period: 15m
          period_count: 20
          hot: 0.5
          cold: 0.99
          std_dev: 2
          signal:
            - bbp
            - mfi
          hot_label: 'Lower Band'
          cold_label: 'Upper Band'
          indicator_label: 'bb inf 5m'
          mute_cold: false    
    rsi:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 50
          cold: 60
          candle_period: 15m 
          period_count: 14
          hot_label: 'Uptrend is coming'
          cold_label: 'Downtred is coming'
          indicator_label: 'rsi'
          mute_cold: false
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 50
          cold: 60
          candle_period: 15m
          period_count: 14
          hot_label: 'Uptrend is coming'
          cold_label: 'Downtred is coming'
          indicator_label: 'rsi'
          mute_cold: false

    bollinger:
        - enabled: false
          candle_period: 15m
          alert_enabled: true
          alert_frequency: once
          period_count: 20
          std_dev: 2
          signal:
            - low_band
            - close
            - up_band
          hot_label: 'Lower Band'
          cold_label: 'Upper Band'
          indicator_label: 'Bollinger Crossing 15m'
          mute_cold: true         
    macd:
        - enabled: false
    stoch_rsi:
        - enabled: false
    momentum:
        - enabled: false
    obv:
        - enabled: false
    mfi:
        - enabled: false
    ichimoku:
        - enabled: false
    iiv:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - iiv
          hot: 4
          cold: 0
          candle_period: 15m
          indicator_label: 'Unusual Volume 5min'  

informants:
    lrsi:
        - enabled: false
    sma:
        - enabled: false       
    ema:
        - enabled: false
    vwap:
        - enabled: false
    bollinger_bands:
        - enabled: false
    ohlcv:  
        - enabled: true
          signal:
            - high
            - low
            - close
          candle_period: 15m
          period_count: 14
        - enabled: false
          signal:
            - high
            - low
            - close
          candle_period: 1h
          period_count: 14
         
conditionals:
    - label: "ALERT \n bbp 0.5 rsi 50 "
      hot:       
        - rsi: 0
        - bbp: 0        
    - label: "ALERT \n iiv 4 rsi 50 "
      hot:     
        - rsi: 1
        - iiv: 0
notifiers:
    telegram_01:
        required:
            token: xxx
            chat_id: xxx 
        optional:
            parse_mode: html
            template: "{{status}}"
```
