### ISSUE TITLE
[FEATURE] Avoiding Spam in Notifications from Conditionals 

### ISSUE THREAD

**Issue by velajos** [w1ld3r/crypto-signal#34]
As is well known, you can mute the notification to the "frequency once" mode, which is excellent to avoid spam. 

But could this feature be implemented from the conditional?

That is, if a pair analyzed at 15 minutes is notified from the conditional, it will be muted for at least 15 minutes or a time interval of the user's choice.

**Comment by w1ld3r** [comment]
You can already use `alert_frequency: once` on your indicators and informants to avoid SPAM.
With this testing conf, I avoid SPAM:
```yml
indicators:
    bbp:
        - enabled: false
    ma_crossover:
        - enabled: false
    rsi:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 100
          cold: 0
          candle_period: 15m 
          period_count: 14
          mute_cold: false
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 100
          cold: 0
          candle_period: 1h
          period_count: 14
          mute_cold: false
    ma_ribbon:
        - enabled: false     
    macd:
        - enabled: false
    iiv:
        - enabled: false
    stoch_rsi:
        - enabled: false
    momentum:
        - enabled: false
    obv:
        - enabled: false
    mfi:
        - enabled: false
    ichimoku:
        - enabled: false

informants:
    lrsi:
        - enabled: false
    sma:
        - enabled: false       
    ema:
        - enabled: false
    vwap:
        - enabled: false
    bollinger_bands:
        - enabled: false
    ohlcv:
        - enabled: false
        
conditionals:
  - label: "Buy"
    hot:
      - rsi: 0
      - rsi: 1
  - label: "Sell"
    cold:
      - rsi: 0
      - rsi: 1
 ```
