### ISSUE TITLE
Haapy to be the first to ask ;) Issue with CONDITIONALS

### ISSUE THREAD

**Issue by bluetyphoon77** [w1ld3r/crypto-signal#4]
Hi again ;)

I've followed your example and it does not work, I still get the individuals notifs.

Is there something I mae wrong ? HEre is my config:

[config.txt](https://github.com/w1ld3r/crypto-signal/files/5629423/config.txt)

thanks in advance for your help

**Comment by w1ld3r** [comment]
It's better if you use this config file (the one in the documentation).

The one you've found was just for dev/debug purpose an so, it's not working with the current release.

```yml
settings:
  log_level: INFO
  update_interval: 120
  start_worker_interval: 2
  market_data_chunk_size: 1
  timezone: Europe/Paris

exchanges:
  kraken:
    required:
      enabled: true
    all_pairs:
      - USD

indicators:
  rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      signal:
        - rsi
      hot: 30
      cold: 70
      candle_period: 1h
      period_count: 14
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      signal:
        - rsi
      hot: 40
      cold: 60
      candle_period: 1d
      period_count: 14
  bollinger:
    - enabled: true
      candle_period: 1h
      alert_enabled: true
      alert_frequency: always
      period_count: 25
      std_dev: 2.5
      signal:
        - low_band
        - close
        - up_band
      mute_cold: false
    - enabled: true
      candle_period: 1d
      alert_enabled: true
      alert_frequency: always
      period_count: 25
      std_dev: 2.5
      signal:
        - low_band
        - close
        - up_band
      mute_cold: false
  aroon_oscillator:
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      sma_vol_period: 50
      period_count: 14
      signal:
        - aroon
      candle_period: 1h

conditionals:
  - label: "Signal to buy"
    hot:
      - rsi: 0
      - rsi: 1
    cold:
      - bollinger: 0
  - label: "Signal to buy"
    hot:
      - rsi: 1
  - label: "Signal to sell"
    cold:
      - rsi: 1
      - rsi: 0
    hot:
      - aroon_oscillator: 0

notifiers:
    telegram:
        required:
            token: X
            chat_id: Y
        optional:
            parse_mode: html
            template: "[{{market}}] {{indicator}} {{status}} {{values}} {{ '\n' -}}"
```
**Just replace the X and Y with your token and chat id.**

You can also modify the timezone if you don't live in Paris.

**Comment by bluetyphoon77** [comment]
Thanks I've tested it. Like you see on my config upload, I use the right values and setings.

Why do I still get individual notifs when I set conditional ?

I'm in Brussels 😉 so ok 😉

________________________________

**Comment by w1ld3r** [comment]
It's because you have to modify `app/defaults.yml` and set `alert_enabled: true` to `alert_enabled: false` or in your `app/config.yml`
define all indicators in `app/defaults.yml` and set them to `enabled: false` if you don't need infos on them or `alert_enabled: false` if you don't want to receive notifications.

**Comment by bluetyphoon77** [comment]
To simplify ;) If I set alert_enabled: false in my config for each individual indicator (rsi and mfi for example) I will ONLY get the conditional notifs ?

**Comment by w1ld3r** [comment]
No you have to set `alert_enabled` to false only for indicators you don't want to receive notifications.
If you want, when I come back home, I can give you an example of the `app/defaults.yml` to use with the config file given above.

**Comment by bluetyphoon77** [comment]
ok thanks. I've tested again, and still not getting the conditional labeled notif ;)
In my config as you can see I've set everything else to false, so notif are fast ! This si great.
 But still not succeeding to make it work for conditionals ! 
Does it mean I have to setup things in defaults ? rather than my personal config ???
ok See you later then, thanks

**Comment by w1ld3r** [comment]
Try this `config.yml`:
```yml
settings:
  log_level: INFO
  update_interval: 900
  start_worker_interval: 2
  market_data_chunk_size: 1
  timezone: Europe/Paris

exchanges:
  kraken:
    required:
      enabled: true
    all_pairs:
      - EUR
    exclude:
      - XBTEUR.d
      - ETHEUR.d
      - USDC
      - USDT
      - MLN

indicators:
  rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: multi
      signal:
        - rsi
      hot: 30
      cold: 70
      candle_period: 1h
      period_count: 14
    - enabled: true
      alert_enabled: true
      alert_frequency: multi
      signal:
        - rsi
      hot: 40
      cold: 60
      candle_period: 1d
      period_count: 14
    - enabled: true
      alert_enabled: true
      alert_frequency: multi
      signal:
        - rsi
      hot: 30
      cold: 70
      candle_period: 1d
      period_count: 14
  momentum:
    - enabled: false
      alert_enabled: false
  mfi:
    - enabled: false
      alert_enabled: false
  obv:
    - enabled: false
      alert_enabled: false
  stoch_rsi:
    - enabled: false
      alert_enabled: false
  macd_cross:
    - enabled: true
      candle_period: 1d
      alert_enabled: true
      alert_frequency: always
      signal:
        - macd
        - signal
      mute_cold: false
  ichimoku:
    - enabled: false
      alert_enabled: false
  iiv:
    - enabled: false
      alert_enabled: false
  ma_crossover:
    - enabled: true
      candle_period: 1d
      alert_enabled: true
      alert_frequency: once
      exponential: true
      ma_fast: 50
      ma_slow: 120
      signal:
        - open
        - close
  bollinger:
    - enabled: true
      candle_period: 1h
      alert_enabled: true
      alert_frequency: always
      period_count: 25
      std_dev: 2.5
      signal:
        - low_band
        - close
        - up_band
      mute_cold: false
    - enabled: true
      candle_period: 1d
      alert_enabled: true
      alert_frequency: always
      period_count: 25
      std_dev: 2.5
      signal:
        - low_band
        - close
        - up_band
      mute_cold: false
  aroon_oscillator:
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      sma_vol_period: 50
      period_count: 14
      signal:
        - aroon
      candle_period: 1h

informants:
    lrsi:
        - enabled: false
    vwap:
        - enabled: false
    sma:
        - enabled: false
    ema:
        - enabled: false
          alert_enabled: false
    bollinger_bands:
        - enabled: false
    ohlcv:
        - enabled: false

conditionals:
  - label: "Buy short"
    hot:
      - rsi: 0
      - rsi: 1
      - bollinger: 0
    cold:
      - aroon_oscillator: 0

notifiers:
    telegram:
        required:
            token: X
            chat_id: Y
        optional:
            parse_mode: html
            template: "[{{market}}] {{indicator}} {{status}} {{values}} {{ '\n' -}}"
```
