### ISSUE TITLE
[HELP] ABOUT CONDITIONAL

### ISSUE THREAD

**Issue by shiftcryptomyid** [w1ld3r/crypto-signal#41]
I'm still confuse about using conditional.. is there any other example or doc beside in config.md

**Comment by w1ld3r** [comment]
In the [example](https://github.com/w1ld3r/crypto-signal/blob/develop/docs/config.md#8-conditionals) there is:
```yml
conditionals:
  - label: "Signal to buy"
    hot:
      - rsi: 0
      - rsi: 1
    cold:
      - bollinger: 0
```
- `label`: The status you want to receive
- `hot`:  Define a list of indicators needed to be hot to receive a notification
- `rsi: 0`: Define the first (index 0) rsi indicator
- `rsi: 1`: Define the second (index 1) rsi indicator
- `cold`:  Define a list of indicators needed to be cold to receive a notification
- `bollinger`: Define the first (index 0) bollinger indicator

So, if rsi_0 and rsi_1 are hot and bollinger_0 is cold, it'll send the notification.
