### ISSUE TITLE
Conditionals notifiers

### ISSUE THREAD

**Issue by ppovedam** [w1ld3r/crypto-signal#45]
**Is your feature request related to a problem? Please describe.**
Hello!

I am trying to enter some conditionals in config.yml. However, although the condition is met, I am not getting any notification. Is there any special syntax for conditionals? My  config.yml is so simple and is just a test with one indicator (obviously, I can obtain the same result with only the indicators, but is a simple way to test conditionals). I would be very grateful if you could give me some indications. Please, find enclosed my config.yml:

```yml
settings:
    log_level: INFO
    update_interval: 60
    start_worker_interval: 2
    market_data_chunk_size: 1
    timezone: Europe/Paris
    enable_charts: true
    market_pairs:
        - ADA/USDT     

exchanges:
    binance:
        required:
            enabled: true

indicators:
    rsi:
        - enabled: false
    stoch_rsi:
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - stoch_rsi
          hot: 20
          cold: 80
          candle_period: 5m
          period_count: 14
    momentum:
        - enabled: false
     macd:
        - enabled: false         
    obv:
        - enabled: false
    mfi:
        - enabled: false
    ichimoku:
        - enabled: false    
    bollinger:
    - enabled: false
    aroon_oscillator:
    - enabled: false

informants:
    lrsi:
        - enabled: false
    sma:
        - enabled: false       
    ema:
        - enabled: false
    vwap:
        - enabled: false
    bollinger_bands:
        - enabled: false
    ohlcv:
        - enabled: false

conditionals:
  - label: "Signal to buy"
    hot:
      - stoch_rsi: 0
      
  - label: "Shell"
    cold:
      - stoch_rsi: 0
          
notifiers:
    telegram:
        required:
            token: xxxxxxx
            chat_id: -xxxxxxx
        optional:
            parse_mode: html
            template: "[{{market}}] {{indicators}} {{status}} {{values}} {{ '\n' -}}" 
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shiftcryptomyid** [comment]
cek this 
[https://github.com/w1ld3r/crypto-signal/issues/41](url)

**Comment by ppovedam** [comment]
> cek this
> [https://github.com/w1ld3r/crypto-signal/issues/41](url)

Sorry, shiftcryptomyid, the link doesn't work

**Comment by shiftcryptomyid** [comment]
can you cek this one

https://github.com/w1ld3r/crypto-signal/issues/41#issuecomment-898749339

**Comment by ppovedam** [comment]
> can you cek this one
> 
> [#41 (comment)](https://github.com/w1ld3r/crypto-signal/issues/41#issuecomment-898749339)

Thanks, shiftcryptomyid, but I've tried with config.yml proposed in issues 8, 23 and 41 that are supposed to work but when I use conditionals crypto-singal still doesn't send notifications. I use w1ld3r branch

**Comment by shiftcryptomyid** [comment]
try this config..
i use it to try conditional and its work.. use webhook notifier

```yml
settings:
    log_level: INFO
    update_interval: 900
    start_worker_interval: 15
    market_data_chunk_size: 1


exchanges:
    binance:
        required:
            enabled: true
        all_pairs:
            - USDT
            #- BTC
        future: true         
        exclude:
            - USDC
            - PAX
            - BUSD
            - TUSD
            - EUR
            - SUSD
            - GBP
            - UTK

indicators:
    bbp:
        - enabled: true
          candle_period: 3m
          alert_enabled: true
          alert_frequency: always
          period_count: 20
          hot: 0
          cold: 0
          std_dev: 2
          signal:
            - bbp
            - mfi
          hot_label: 'Lower Band'
          cold_label: 'Upper Band'
          indicator_label: 'Bollinger Crossing'
          mute_cold: false
    ma_crossover:
        - enabled: false
    stoch_rsi:
        - enabled: false
    adx:
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - adx
            - pdi
            - ndi
          hot: 25
          cold: 25
          candle_period: 3m
          period_count: 14
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - adx
            - pdi
            - ndi
          hot: 25
          cold: 25
          candle_period: 1m
          period_count: 14
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - adx
            - pdi
            - ndi
          hot: 25
          cold: 25
          candle_period: 5m
          period_count: 14
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - adx
            - pdi
            - ndi
          hot: 25
          cold: 25
          candle_period: 15m
          period_count: 14
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - adx
            - pdi
            - ndi
          hot: 25
          cold: 25
          candle_period: 30m
          period_count: 14
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - adx
            - pdi
            - ndi
          hot: 25
          cold: 25
          candle_period: 1h
          period_count: 14
    rsi:
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - rsi
          hot: 50
          cold: 50
          candle_period: 3m
          period_count: 14
          mute_cold: false
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - rsi
          hot: 50
          cold: 50
          candle_period: 1m
          period_count: 14
          mute_cold: false
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - rsi
          hot: 50
          cold: 50
          candle_period: 5m
          period_count: 14
          mute_cold: false
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - rsi
          hot: 50
          cold: 50
          candle_period: 15m
          period_count: 14
          mute_cold: false
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - rsi
          hot: 50
          cold: 50
          candle_period: 30m
          period_count: 14
          mute_cold: false
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - rsi
          hot: 50
          cold: 50
          candle_period: 1h
          period_count: 14
          mute_cold: false
    stochrsi_cross:
        - enabled: false
    momentum:
        - enabled: false
    macd:
        - enabled: false
    ma_ribbon:
        - enabled: false 
    iiv:
        - enabled: false
    obv:
        - enabled: false
    mfi:
        - enabled: false
    ichimoku:
        - enabled: false

informants:
    lrsi:
        - enabled: false
    sma:
        - enabled: false 
    ema:
        - enabled: false

    vwap:
        - enabled: false
    bollinger_bands:
        - enabled: false
    ohlcv:
        - enabled: true
          signal:
            - high
            - low
            - close
          candle_period: 1m
          period_count: 14
        

 

conditionals:
-label: "Signal to buy"
    hot:
      - bbp: 0
      - rsi: 0
      - rsi: 1
      - rsi: 2
      - rsi: 3
      - rsi: 4
      - rsi: 5
      - adx: 0
      - adx: 1
      - adx: 2
      - adx: 3
      - adx: 4
      - adx: 5
      
-label: "Signal to sell"
    cold:
      - bbp: 0
      - rsi: 0
      - rsi: 0
      - rsi: 1
      - rsi: 2
      - rsi: 3
      - rsi: 4
      - rsi: 5
      - adx: 0
      - adx: 1
      - adx: 2
      - adx: 3
      - adx: 4
      - adx: 5


notifiers:
    webhook:
        required:
            url: https://shiftcrypto.my.id/newtest/newfuture1.php
        optional:
            username: 
            password: 
```


its take some time
and i got this data


`[{"values": [{"rsi": "54.91"}, {"rsi": "54.91"}, {"bbp": "0.69", "mfi": "54.07"}, {"adx": "13.65", "pdi": "594.27", "ndi": "552.72"}, {"rsi": "50.64"}, {"adx": "18.71", "pdi": "447.95", "ndi": "437.19"}, {"rsi": "58.68"}, {"adx": "22.75", "pdi": "346.47", "ndi": "269.12"}, {"rsi": "61.18"}, {"adx": "20.64", "pdi": "1125.73", "ndi": "869.02"}, {"rsi": "57.98"}, {"adx": "15.80", "pdi": "1265.89", "ndi": "832.03"}, {"rsi": "55.94"}, {"adx": "12.27", "pdi": "2053.54", "ndi": "1663.40"}], "indicator": ["rsi", "rsi", "bbp", "adx", "rsi", "adx", "rsi", "adx", "rsi", "adx", "rsi", "adx", "rsi", "adx"], "price_value": {"3m": {}, "1m": {"high": 0.10292, "low": 0.10277, "close": 0.10288}, "5m": {}, "15m": {}, "30m": {}, "1h": {}}, "exchange": "binance", "market": "RVN/USDT", "base_currency": "RVN", "quote_currency": "USDT", "prices": "", "decimal_format": "%.5f", "status": "Signal to sell"}]`
