### ISSUE TITLE
[BUG] can't open file 'app.py': [Errno 2] No such file or directory  

### ISSUE THREAD

**Issue by beta323** [w1ld3r/crypto-signal#47]
**Describe the bug**
Upon returning the terminal command to run, "docker run --rm -ti -v $PWD/app:/app dev/crypto-signals:latest", I'm receiving Traceback errors. Did steps all in order on my OSX, upgraded to python3, git, pip... 

**config.yml**
```yml
settings:
  log_level: INFO
  update_interval: 100
  market_pairs:
    - BNB/USDT
    - SHIB/USDT
    - ONT/USDT

exchanges:
  Binance:
    required:
      enabled: true

indicators:
    momentum:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - momentum
          candle_period: 1h
          period_count: 18
    rsi:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 32
          cold: 80
          candle_period: 1h 
          period_count: 18
          hot: 0
          cold: 0

Informants:
    ema:
	- enabled: true
	  signal:
	    - ema
	  candle_period: 1hr
	  period_count: 18
    vwap:
        - enabled: true
          signal:
            - vwap
          candle_period: 1d
          period_count: 15
    BOL_BAND:
        - enabled: true
          signal:
            - middleband
          candle_period: 1hr
          period_count: 18

crossovers:
    std_crossover:
        - enabled: false
          alert_enabled: true
          alert_frequency: once
          key_indicator: ema
          key_indicator_index: 0
          key_indicator_type: informants
          key_signal: ema
          crossed_indicator: sma
          crossed_indicator_index: 0
          crossed_indicator_type: informants
          crossed_signal: sma



notifiers:
    telegram:
        required:
            token: XXXX
            chat_id: XXXX
        optional:
            parse_mode: html
            template: "{{exchange}}-{{market}}-{{indicator}}-{{indicator_number}} is {{status}}!{{ '\n' -}}"
```

**Machine**
 - macOS Catalina, 10.15.3
 - crypto-signal branch
 - Docker version 4.1.1

**Additional context**
Only modifications have been done to the config.yml folder, I copied it directly into the "app" folder.
Within Dockers image itself, logs states "python: can't open file 'app.py': [Errno 2] No such file or directory".
