### ISSUE TITLE
[BUG] Failed to run

### ISSUE THREAD

**Issue by asmyshlyaev177** [w1ld3r/crypto-signal#48]
**Describe the bug**
Trying to run with `docker run --rm -v $PWD/app:/app dev/crypto-signals:latest`

Got error
```
Traceback (most recent call last):
  File "app.py", line 108, in <module>
    main()
  File "app.py", line 24, in main
    config = Configuration()
  File "/app/conf.py", line 68, in __init__
    if exchange not in self.exchanges:
TypeError: argument of type 'NoneType' is not iterable
```

Config that worked with original Crypto-Signal, config in root directory.

**To Reproduce**
1. Clone repo
2. `docker build -t dev/crypto-signals:latest .`
3. Add config.yml
3. docker run `docker run --rm -v $PWD/app:/app dev/crypto-signals:latest`
4. Error

**Expected behavior**

**config.yml**
```yml
settings:
    log_level: WARN
    update_interval: 90
    # enable_charts: true
    market_pairs:
        - BTC/USDT

exchanges:
    binance:
        required:
            enabled: true

indicators:
    macd_cross:
        - enabled: true
          candle_period: 5m
          alert_enabled: true
          alert_frequency: always
          signal:
            - macd
            - signal
          hot_label: 'Uptrend is coming'
          cold_label: 'Downtred is coming'
          indicator_label: 'MACD Cross 5m'
          mute_cold: false
    mfi:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - mfi
          hot: 25
          cold: 80
          candle_period: 5m
          period_count: 14
    stoch_rsi:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - stoch_rsi
          hot: 20
          cold: 80
          candle_period: 5m
          period_count: 14
    iiv:
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - iiv
          hot: 8
          cold: 0
          candle_period: 1m

crossovers:
    std_crossover:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          key_indicator: macd
          key_indicator_index: 0
          key_indicator_type: indicators
          key_signal: macd
          crossed_indicator: macd
          crossed_indicator_index: 1
          crossed_indicator_type: indicators
          crossed_signal: macdsignal

informants:
    ohlcv:
        - enabled: true
          signal:
            - high
            - low
            - close
          candle_period: 5m
          period_count: 14
        - enabled: true
          signal:
            - high
            - low
            - close
          candle_period: 1m
          period_count: 14  

notifiers:
    telegram:
        required:
            token: 20855*****
            chat_id: 192*****
        optional:
            parse_mode: html
            template: "Prices: [{{prices}}] {{market}}-{{indicator}}-{{indicator_number}} is {{status}}! ({{values}}){{ '\n' -}}" 
    stdout:
        required:
            enable: true
        optional:
            template: "{{exchange}}-{{market}}-{{indicator}}-{{indicator_number}} is {{status}}!{{ '\n' -}}"

# template: "Prices: [{{prices}}] {{analysis.config.candle_period}} {{market}}-{{indicator}}-{{indicator_number}} is {{status}}! ({{values}}){{ '\n' -}}" 
```

**Machine**
 - Ubuntu 21
 - crypto-signal branch *Develop*
 - Docker version 20.10.9
