### ISSUE TITLE
Problem with ichimoku

### ISSUE THREAD

**Issue by mosa789** [w1ld3r/crypto-signal#53]
Hello 
There's a problem when I change alert_frequency in Ichimoku indicator to once then I don't receive any signal at the moment of crossing Senko a and b. What's the problem?

Here is my config

```
settings:
    log_level: INFO
    update_interval: 60
    start_worker_interval: 1
    market_data_chunk_size: 1

exchanges:
    binance:
        required:
            enabled: true
        all_pairs:
            - USDT
        future: true            
        exclude:
            - USDC
            - PAX
            - BUSD
            - TUSD
            - EUR
            - SUSD
            - GBP
            - UTK
            
        
        
indicators:
    bbp:
        - enabled: false
    rsi:
        - enabled: false    
    ichimoku:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - leading_span_a
            - leading_span_b
          hot: true
          cold: true
          candle_period: 5m
    iiv:
        - enabled: false
    stoch_rsi:
        - enabled: false
    momentum:
        - enabled: false
    macd:
        - enabled: false
    obv:
        - enabled: false
    mfi:
        - enabled: false
informants:
    lrsi:
        - enabled: false
    vwap:
        - enabled: false
    sma:
        - enabled: false
    ema:
        - enabled: false
    bollinger_bands:
        - enabled: false
    ohlcv:
        - enabled: true
          signal:
            - high
            - low
            - close
            - open
            - volume
          candle_period: 5m
          period_count: 100
        - enabled: true
          signal:
            - high
            - low
            - close
            - open
            - volume
          candle_period: 1h
          period_count: 20  
        
conditionals:
  - label: "BUY Signal5"
    hot:
      - ichimoku: 0
  - label: "Sell Signal5"
    cold:
      - ichimoku: 0
```
