### ISSUE TITLE
[BUG] not getting the right STOCHRSI values

### ISSUE THREAD

**Issue by bluetyphoon77** [w1ld3r/crypto-signal#6]
**Describe the bug**
I've asked the bot to get the 3 STOCHRSI values (stochrsi, k, d) and all are wrong

**To Reproduce**
Easy. Just tell me if you have the right one yourself. It has nothing to do with installation. 
Probably how we set up STOCH .. and WHAT we can set up to have accuracy.

**Expected behavior**
Check this.
When bot started. I get for example for HBAR/USDT on binance 
stoch_rsi #0: 81.90397794/68.25484126/60.94965080
first = stoch, then k, then d

In tradingview
k = 56.30
d = 46.47

So, TOTALLY WRONG ... weird.... not even ONE value matches !

**config.yml**
```
# Copy this file to config.yml to get started and then add your own configuration.
# Full documentation here: https://github.com/CryptoSignal/crypto-signal/blob/master/docs/config.md

settings:
  log_level: INFO
  update_interval: 3600
  timezone: Europe/Paris
  market_pairs:
    - THETA/BTC
    - UTK/USDT
    - VIA/BTC
    - POWR/BTC
    - NXS/BTC
    - NAV/BTC
    - STEEM/BTC
    - VIB/BTC
    - BCPT/BTC
    - DGB/BTC
    - APPC/BTC
    - SNX/USDT
    - KNC/USDT
    - ICX/USDT
    - HBAR/USDT

exchanges:
  binance:
    required:
      enabled: true

notifiers:
    telegram:
        required:
            token: 
            chat_id: 
        optional:
            parse_mode: html
            template: "{{exchange}} - {{market}} - {{indicator_label}} - {{values}} - {{hot_cold_label}} - {{conditionals}}  "
          
indicators:
    rsi:
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - rsi
          hot: 40
          cold: 75
          hot_label: 'GOOD buy opportunity!'
          cold_label: 'GOOD sell opportunity!'
          indicator_label: 'RSI Daily'
          candle_period: 1d
          period_count: 14
          mute_cold: false
  
    mfi:
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - mfi
          hot: 25
          cold: 75
          hot_label: 'GOOD buy opportunity!'
          cold_label: 'GOOD sell opportunity!'
          indicator_label: 'MFI Daily'
          candle_period: 1d
          period_count: 12
          mute_cold: false
    
    stoch_rsi:
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - stoch_rsi
            - slow_k
            - slow_d         
          hot: 25
          cold: 80
          hot_label: 'GOOD buy opportunity!'
          cold_label: 'GOOD sell opportunity!'
          indicator_label: 'STOCH Daily'
          candle_period: 1d
          period_count: 14
          mute_cold: false

    macd:
        - enabled: false
    momentum:
        - enabled: false
    obv:
        - enabled: false    
    ichimoku:
        - enabled: false
    iiv:
        - enabled: false

informants:
    lrsi:
        - enabled: false
    vwap:
        - enabled: false
    sma:
        - enabled: false
    ema:
        - enabled: false
    bollinger_bands:
        - enabled: false
    ohlcv:
        - enabled: false


conditionals:  
  - label: "2 CHECKMARKS for a GOOD sell"
    cold:
      - stoch_rsi: 0
    cold:
      - mfi: 0

```

**Desktop**
 - ubuntu 16.4
 - crypto-signal branch : yours !
 - Docker version : I don't know

DONE ! As you asked.
Hope you'll be able to help
thanks
PS: I just removed telgram info
