### ISSUE TITLE
[BUG] defaults.yml in documentation

### ISSUE THREAD

**Issue by kartun83** [w1ld3r/crypto-signal#63]
In documentation it's not stated that values from config.yml overwrite structure of defaults.yml.
So, if in defaults.yml some indicator is **enabled**, but in config.yml it's not defined (the expected behavior = _disabled_) value is taken from defaults.yml.
This, in turn leads to consequences - price_values for notification is calculated only if ohlcv for same period is explicitly enabled

**Comment by kartun83** [comment]
Found another glitch between defaults.yml and config.yml:

defaults.yml
```
  obv:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - obv
      hot: 0
      cold: 0
      candle_period: 1d
  ohlcv:
    - enabled: true
      signal:
        - close
      candle_period: 1d
      period_count: 15
```

config.yml
  ```
obv - not defined
  ohlcv:
    - enabled: true
      signal:
        - close
      candle_period: 5m
      period_count: 15
```

price_values for notification for obv is not available
